// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSYhNBFaUGKgKSGQFiu9ohyXy1BNxm4BM',
    appId: '1:433476071003:web:ed735bd4b05de5a5e2d97e',
    messagingSenderId: '433476071003',
    projectId: 'petcare-acb8d',
    authDomain: 'petcare-acb8d.firebaseapp.com',
    storageBucket: 'petcare-acb8d.appspot.com',
    measurementId: 'G-XTQKZFY1B2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmhrSLuYVuECXZuuM2qKO-ZRMUtEKmmE8',
    appId: '1:433476071003:android:5f286b4e9cdf0eace2d97e',
    messagingSenderId: '433476071003',
    projectId: 'petcare-acb8d',
    storageBucket: 'petcare-acb8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtDo4hoCVJEfc4HALw33QiXVsdK3x3Cbs',
    appId: '1:433476071003:ios:f76bddc04f11c21de2d97e',
    messagingSenderId: '433476071003',
    projectId: 'petcare-acb8d',
    storageBucket: 'petcare-acb8d.appspot.com',
    iosClientId:
        '433476071003-2p6g6p6g74fnn01nuj81s2r2esdghs9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.petcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtDo4hoCVJEfc4HALw33QiXVsdK3x3Cbs',
    appId: '1:433476071003:ios:208aa5f725a18431e2d97e',
    messagingSenderId: '433476071003',
    projectId: 'petcare-acb8d',
    storageBucket: 'petcare-acb8d.appspot.com',
    iosClientId:
        '433476071003-fp3g9dit5t3pqnr62foqo9oqur2qa970.apps.googleusercontent.com',
    iosBundleId: 'com.example.petcare.RunnerTests',
  );
}
